# Generated by Django 5.0.6 on 2024-07-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campeonato', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipo',
            new_name='equipo_futbol',
        ),
    ]
